#!/usr/bin/env python
from subprocess import call
import sys
def init():
  try:
    host = raw_input("[>] Host address: ")
    min_port = raw_input("[>] Minimum port: ")
    max_port = raw_input("[>] Maximum port: ")
    call("python /usr/haxxor/modules/scanning/.portscan " + host + " " + min_port + " " + max_port, shell=True)
  except KeyboardInterrupt:
    sys.exit(0)
# LOL
