#!/usr/bin/env python
import sys, time
from datetime import datetime 
from socket import *

host = ''
min_port = raw_input("[>] Mininum port: ")
max_port = raw_input("[>] Maximum port: ")

def scan_host(host, port, r_code = 1):
  try:
    s = socket(AF_INET, SOCK_STREAM)
    code = s.connect_ex((host, port))
    if(code == 0):
      r_code = code
    s.close
  except Execption, e:
    pass
  return r_code
try:
  host = raw_input("[>] Target Host address: ")
except KeyboardInterrupt:
  print("[!] Exiting")
  sys.exit(1)
hostip = gethostbyname(host)
print("\n[*] Host: %s IP:  %s" % (host, hostip))
print("\n[*] Scanning started At %s....\n" %(time.strftime("%H:%M:%S")))
start_time = datetime.now

for port in range(min_port, max_port):
  try:
    response = scan_host(host, port)
    if(response == 0):
      print("[*] Port %d Open" % (port))
  except Execption, e:
    pass
stop_time = datetime.now()
total_time_duration = stop_time - start_time
print("[*] Scanning finished at %s ..." % (time.strftime(%H:%M:%S")))
print("[*] Scanning duration: %s ..." % (total_time_duration))
