#!/usr/bin/env python
from subprocess import call
from termcolor import colored
import time

print colored("[!] I did NOT write venom", "red")
print colored("[!] It was written by www.sourceforge.com/u/peterubuntu10/profile", "red")
print colored("[!] Thanks peterubuntu10!", "red")
time.sleep(3)

call("./usr/haxxor/post/windows/venom.sh", shell=True)
